Mxonline2/urls.py
from django.conf.urls import url,include
import xadmin

from user_profile.views import IndexView,LoginView,RegisterView,LogoutView,ActiveUserView,ForgetPwdView,\
    ResetView,ModifyPwdView

urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    #   首页url配置
    url(r'^$',IndexView.as_view(),name='index'),

    #   user_profile    app的url配置
    url(r'^users/',include('user_profile.urls',namespace='users')),

    #   登录页面跳转url不要直接调用，而只是指向这个函数对象
    #   基于类方法实现登陆
    url(r'^login/$',LoginView.as_view(),name='login'),

    #   基于类方法实现注册
    url(r'^register/$',RegisterView.as_view(),name='register'),

    #   基于类方法实现退出
    url(r'^logout/$',LogoutView.as_view(),name='logout'),

    #   验证码的url配置
    url(r'^captcha/',include('captcha.urls')),

    #   激活用户url
    url(r'^active/(?P<active_code>.*)/$',ActiveUserView.as_view(),name='user_active'),

    #   忘记密码url
    url(r'^forget/$',ForgetPwdView.as_view(),name='forget_pwd'),

    #   重置密码url
    url(r'^reset/(?P<active_code>.*)/$',ResetView.as_view(),name='reset_pwd'),

    #   修改密码url
    url(r'^modify_pwd/$',ModifyPwdView.as_view(),name='modify_pwd'),

    #   公开课app的url
    url(r'^course/',include('course.urls',namespace='course')),

    #   课程机构app的url
    url(r'^org/',include('organization.urls',namespace='org')),
]

#   全局404配置
handler404 = "user_profile.views.page_not_found"
handler500 = "user_profile.views.page_error"

course/urls.py
from django.conf.urls import url
from course.views import CourseListView,CourseDetailView,CourseLessonView,CourseVideoView,CourseCommentView,\
    AddCommentView

urlpatterns = [
    #   公开课程列表
    url(r'^list/$',CourseListView.as_view(),name='list'),

    #   课程详情页
    url(r'^course/(?P<course_id>\d+)/$',CourseDetailView.as_view(),name='course_detail'),

    #   课程章节信息页
    url(r'^lesson/(?P<course_id>\d+)/$',CourseLessonView.as_view(),name='course_lesson'),

    #   课程视频列表页
    url(r'^video/(?P<video_id>\d+)/$',CourseVideoView.as_view(),name='course_video'),

    #   课程评论列表页
    url(r'^comment/(?P<course_id>\d+)/$',CourseCommentView.as_view(),name='course_comment'),

    #   添加评论
    url(r'^add_comment/$',AddCommentView.as_view(),name='add_comment'),

]

extra_app/DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

organization/urls.py
from django.conf.urls import url
from organization.views import OrgListView,AddUserAskView,OrgHomeView,OrgCourseView,OrgTeacherView,OrgDescView,\
    AddFavView,TeacherListView,TeacherDetailView

urlpatterns = [
    #   授课机构列表
    url(r'^list/$',OrgListView.as_view(),name='org_list'),

    #   学习咨询
    url(r'^add_ask/$',AddUserAskView.as_view(),name='add_ask'),

    #   机构详情页，
    url(r'^home/(?P<org_id>\d+)/$',OrgHomeView.as_view(),name='org_home'),

    #   机构课程列表
    url(r'^course/(?P<org_id>\d+)/$',OrgCourseView.as_view(),name='org_course'),

    #   机构介绍列表页
    url(r'^desc/(?P<org_id>\d+)/$',OrgDescView.as_view(),name='org_desc'),

    #   机构讲师列表
    url(r'^teacher/(?P<org_id>\d+)/$',OrgTeacherView.as_view(),name='org_teacher'),

    #   添加收藏
    url(r'^add_fav/$',AddFavView.as_view(),name='add_fav'),

    #   讲师列表url配置
    url(r'^teacher/list/$',TeacherListView.as_view(),name='teacher_list'),

    #   教师详情url配置
    url(r'teacher/detail/(?P<teacher_id>\d+)/$',TeacherDetailView.as_view(),name='teacher_detail'),
]

user_profile/urls.py
from django.conf.urls import url

from user_profile.views import UserInfoView,MyCourseView,MyFavOrgView,MyFavTeacherView,MyFavCourseView,\
    MyMessageView,UploadImageView,UpdatePwdView,UpdateEmailView,SendEmailCodeView

urlpatterns = [
    #   用户信息
    url(r'^info/$',UserInfoView.as_view(),name='user_info'),

    #   用户中心头像上传
    url(r'^image/upload/$',UploadImageView.as_view(),name='image_upload'),

    # 用户个人中心修改密码
    url(r'^update/pwd/$', UpdatePwdView.as_view(), name="update_pwd"),

    #   邮箱验证码发送
    url(r'^sendemail_code/$',SendEmailCodeView.as_view(),name='sendemail_code'),

    #   用户中心修改邮箱
    url(r'^update_email/$',UpdateEmailView.as_view(),name='update_email'),

    #   用户中心我的课程
    url(r'^mycourse/$',MyCourseView.as_view(),name='mycourse'),

    #   用户中心我的收藏的课程机构
    url(r'^myfav/org/$',MyFavOrgView.as_view(),name='myfav_org'),

    #   用户中心我的收藏的授课教师
    url(r'^myfav/teacher/$',MyFavTeacherView.as_view(),name='myfav_teacher'),

    #   用户中心我的收藏的公开课程
    url(r'^myfav/course/$',MyFavCourseView.as_view(),name='myfav_course'),

    #   用户中心我的消息
    url(r'^my_message/$',MyMessageView.as_view(),name='my_message'),

]

course/models.py
from django.db import models
from organization.models import CourseOrg,Teacher

# Create your models here.

#   课程信息表
class Course(models.Model):
    #   自定义选择规则
    DEGREE_CHOICES = (
        ('cj','初级'),
        ('zj','中级'),
        ('gj','高级')
    )
    course_org = models.ForeignKey(CourseOrg,verbose_name="所属机构",null=True,blank=True)
    teacher = models.ForeignKey(Teacher,verbose_name='讲师',null=True,blank=True)
    name = models.CharField(max_length=10,verbose_name='课程名')
    is_banner = models.BooleanField(default=False,verbose_name='是否轮播')
    desc = models.CharField(max_length=520,verbose_name='课程描述')
    # TextField允许我们不输入长度。可以输入到无限大。暂时定义为TextFiled，之后更新为富文本
    # 修改imagepath,不能传y m 进来，不能加斜杠是一个相对路径，相对于setting中配置的mediaroot
    detail = models.TextField(verbose_name="课程详情")
    degree = models.CharField(choices=DEGREE_CHOICES,max_length=10,verbose_name="难度")
    #   使用分钟数做后台记录(存储最小单位),前台转换
    learn_times = models.IntegerField(default=0,verbose_name="学习时长(分钟数)")
    #   保存学习人数：从点击开始学习算起
    students = models.IntegerField(default=0,verbose_name="学习人数")
    fav_nums = models.IntegerField(default=0,verbose_name="收藏人数")
    category = models.CharField(max_length=20,verbose_name="课程类别")
    you_need_know = models.CharField(max_length=500,default="一颗勤学的心和坚持不懈的精神是本课程必要前提",verbose_name="课程须知")
    teacher_tell = models.CharField(max_length=300,default="按时交作业,不然叫家长",verbose_name="老师告诉你")
    tag = models.CharField(max_length=15,verbose_name="课程标签")
    course_img = models.ImageField(
        upload_to="course/%Y/%m",
        verbose_name="课程封面",
        max_length=100
    )
    #   保存点击量
    click_nums = models.IntegerField(default=0,verbose_name="点击数")
    add_time = models.DateField(auto_now_add=True,verbose_name="添加时间")

    def get_zj_nums(self):
        return self.lesson_set.all().count()
    get_zj_nums.short_description = '章节数'

    def go_to(self):
        from django.utils.safestring import mark_safe
        # 如果不mark safe。会对其进行转义
        return  mark_safe("<a href='http://blog.mtianyan.cn'>跳转</>")
    go_to.short_description = "跳转"

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '课程'
        verbose_name_plural = verbose_name

#   轮播图
class BannerCourse(Course):
    class Meta:
        verbose_name = "轮播课程"
        verbose_name_plural = verbose_name
        proxy = True

#   章节
class Lesson(models.Model):
    #   因为一个课程对应很多章节，在章节表中将课程设置为外键.
    course = models.ForeignKey(Course,verbose_name="课程")
    name = models.CharField(max_length=10,verbose_name="章节名")
    add_time = models.DateField(auto_now_add=True,verbose_name="添加时间")

    def __str__(self):
        return '《{0}》课程的章节 >> {1}'.format(self.course,self.name)

    class Meta:
        verbose_name = '章节'
        verbose_name_plural = verbose_name

#   章节视频
class Video(models.Model):
    #   一个章节对应很多视频,所以讲章节设置为外键
    lesson = models.ForeignKey(Lesson,verbose_name="章节")
    name = models.CharField(max_length=10,verbose_name="视频名")
    url = models.CharField(max_length=100,default="https://www.cnblogs.com/Tridents/",verbose_name="访问地址")
    #   使用分钟做后台转换(存储最小单位)前台转换
    learn_times = models.IntegerField(default=0,verbose_name="学习时长(分钟数)")
    add_time = models.DateField(auto_now_add=True,verbose_name="添加时间")

    def __str__(self):
        return '《{0}》章节的视频 >> {1}'.format(self.lesson,self.name)

    class Meta:
        verbose_name = '章节视频'
        verbose_name_plural = verbose_name

#   课程资源
class CourseResource(models.Model):
    #   一个课程对应多个资源，所以在这里将课程设置为外键
    course = models.ForeignKey(Course,verbose_name="课程")
    name = models.CharField(max_length=10,verbose_name="名称")
    #   此处直接定义为文件类型的filed,后台有按钮可直接上传
    download = models.FileField(
        upload_to="course/resourse/%Y/%m",
        verbose_name="资源文件",
        max_length=100
    )
    add_time = models.DateField(auto_now_add=True,verbose_name="添加时间")

    def __str__(self):
        return '《{0}》课程的资源 >> {1}'.format(self.course,self.name)

    class Meta:
        verbose_name = '课程资源'
        verbose_name_plural = verbose_name

templates/course-comment.html
{% extends 'course-list.html' %}
{% load static %}
{% block title %}<title>公开课评论 - 慕学在线网</title>{% endblock %}
{% block custom_css %}
    <link rel="stylesheet" type="text/css" href="/static/css/muke/base.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/muke/common-less.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/muke/course/learn-less.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/muke/course/course-comment.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/mooc.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/muke/course/common-less.css">
{% endblock %}
{% block two %}
    <li><a href="{% url 'course:list' %}">公开课程</a>></li>
    <li><a href="{% url 'course:course_detail' course.id %}">{{ course.name }}</a>></li>
    <li>课程评论</li>
{% endblock %}
{% block section %}
<div id="main">
    <div class="course-infos">
        <div class="w pr">
            <div style="height: 15px" class="path">
            </div>
            <div class="hd">
                <h2 class="l">{{ course.name }}</h2>
            </div>
            <div class="statics clearfix">
                <div class="static-item ">
                    <span class="meta-value"><strong>{{ course.get_degree_display }}</strong></span>
                    <span class="meta">难度</span>
                    <em></em>
                </div>
                <div class="static-item static-time">
                    <span class="meta-value">{{ course.learn_times }}分钟</span>
                    <span class="meta">时长</span>
                    <em></em>
                </div>
                <div class="static-item">
                    <span class="meta-value"><strong>{{ course.students }}</strong></span>
                    <span class="meta">学习人数</span>
                    <em></em>
                </div>
            </div>
        </div>
    </div>
    <div class="course-info-main clearfix w has-progress">

        <div class="info-bar clearfix">
            <div class="content-wrap clearfix">
                <div class="content">
                    <div class="mod-tab-menu">
                        <ul class="course-menu clearfix">
                            <li><a class="ui-tabs-active " id="learnOn"  href="{% url 'course:course_lesson' course.id %}"><span>章节</span></a></li>
                            <li><a id="commentOn" class="active" href="{% url 'course:course_comment' course.id %}"><span>评论</span></a></li>
                        </ul>
                    </div>

                    <!--发布评论-->
                    <div id="js-pub-container" class="issques clearfix js-form">
                        <div class="wgt-ipt-wrap pub-editor-wrap " id="js-pl-input-fake">
                            <textarea id="js-pl-textarea" class="" placeholder="扯淡、吐槽、表扬、鼓励……想说啥就说啥！" ></textarea>
                        </div>
                        <input type="button" id="js-pl-submit" class="pub-btn" data-cid="452" value="发表评论">
                        <p class="global-errortip js-global-error"></p>
                    </div>
                    <div id="course_note">
                        <ul class="mod-post" id="comment-list">
                            {% for all_comment in all_comments %}
                            <li class="post-row">
                                <div class="media">
                                    <span target="_blank"><img src='{% static all_comment.user.head_image %}' width='40' height='40' /></span>
                                </div>
                                <div class="bd">
                                    <div class="tit">
                                        <span target="_blank">{{ all_comment.user.nick_name }}</span>
                                    </div>
                                    <p class="cnt">{{ all_comment.comments }}</p>
                                    <div class="footer clearfix">
                                        <span title="创建时间" class="l timeago">时间：{{ all_comment.add_time }}</span>
                                    </div>
                                </div>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>

                </div>
                <div class="aside r">
                    <div class="bd">

                        <div class="box mb40">
                        <h4>资料下载</h4>
                        <ul class="downlist">
                            {% for all_resource in all_resources %}
                            <li>
                                <span ><i class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp;{{ all_resource.name }}</span>
                                <a href="{% static all_resource.download %}" class="downcode" target="_blank" download="" data-id="274" title="">下载</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                        <div class="box mb40">
                        <h4>讲师提示</h4>
                        <div class="teacher-info">
                            <a href="/u/315464/courses?sort=publish" target="_blank">
                                <img src='{% static course.teacher.image %}' width='80' height='80' />
                            </a>
        <span class="tit">
          <a href="/u/315464/courses?sort=publish" target="_blank">{{ course.teacher.name }}</a>
        </span>
                            <span class="job">{{ course.teacher.work_position }}</span>
                        </div>
                        <div class="course-info-tip">
                            <dl class="first">
                                <dt>课程须知</dt>
                                <dd class="autowrap">python基础你需要有</dd>
                            </dl>
                            <dl>
                                <dt>老师告诉你能学到什么？</dt>
                                <dd class="autowrap">{{ course.teacher_tell }}</dd>
                            </dl>
                        </div>
                    </div>


                        <div class="cp-other-learned  js-comp-tabs">
                            <div class="cp-header clearfix">
                                <h2 class="cp-tit l">该课的同学还学过</h2>
                            </div>
                            <div class="cp-body">
                                <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course" style="display: block">
                                    <!-- img 200 x 112 -->
                                    <ul class="other-list">
                                        {% for relate_course in relate_courses %}
                                        <li class="curr">
                                            <a href="{% url 'course:course_detail' relate_course.id %}" target="_blank">
                                                <img src="{% static relate_course.course_img %}" alt="{{ relate_course.name }}">
                                                <span class="name autowrap">{{ relate_course.name }}</span>
                                            </a>
                                        </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                                <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="plan">
                                    <ul class="other-list">
                                        <li class="curr">
                                            <a href="/course/programdetail/pid/31?src=sug" target="_blank">
                                                <img src="http://img.mukewang.com/56551e6700018b0c09600720-240-135.jpg" alt="Java工程师">
                                                <span class="name autowrap">Java工程师</span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                    </div>    </div>
            </div>
            <div class="clear"></div>

        </div>

    </div>
</div>
{% endblock %}
{% block custom_js %}
<script type="text/javascript">
    //添加评论
    $('#js-pl-submit').on('click', function(){
        var comments = $("#js-pl-textarea").val()
        if(comments == ""){
            alert("评论不能为空")
            return
        }
        $.ajax({
            cache: false,
            type: "POST",
            url:"{% url 'course:add_comment' %}",
            data:{'course_id':{{ course.id }}, 'comments':comments},
            async: true,
            beforeSend:function(xhr, settings){
                xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
            },
            success: function(data) {
                if(data.status == 'fail'){
                    if(data.msg == '用户未登录'){
                        window.location.href="/login/?next={{ request.path }}";
                    }else{
                        alert(data.msg)
                    }

                }else if(data.status == 'success'){
                    window.location.reload();//刷新当前页面.
                }
            },
        });
    });

</script>
{% endblock %}

templates/index.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>课程机构列表 - 慕学在线网</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/animate.css">
	<link rel="stylesheet" type="text/css" href="/static/css/style.css">
    
    <script src="/static/js/jquery.min.js" type="text/javascript"></script>
    <script src="/static/js/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>

</head>
<body>
<section class="headerwrap ">
    <header>
		<div  class=" header">
 			<div class="top">
				<div class="wp">
					<div class="fl"><p>服务电话：<b>33333333</b></p></div>
						{% if request.user.is_authenticated %}
						    <div class="personal">
                                <dl class="user fr">
                                    <dd>{{ request.user }}<img class="down fr" src="/static/images/top_down.png"/></dd>
                                    <dt><img width="20" height="20" src="{% static request.user.head_image %}"/></dt>
                                </dl>
                                <div class="userdetail">
                                    <dl>
                                        <dt><img width="80" height="80" src="{% static request.user.head_image %}"/></dt>
                                        <dd>
                                            <h2>{{ request.user }}</h2>
                                            <p>{{ request.user.username }}</p>
                                        </dd>
                                    </dl>
                                    <div class="btn">
                                        <a class="personcenter fl" href="{% url 'users:user_info' %}">进入个人中心</a>
                                        <a class="fr" href="{% url 'logout' %}">退出</a>
                                    </div>
                                </div>
                            </div>
                        {% else %}
                        <!--登录后跳转-->

                            <a style="color:white" class="fr registerbtn" href="{% url 'register' %}">注册</a>
                            <a style="color:white" class="fr loginbtn" href="{% url 'login' %}">登录</a>
						{% endif %}



				</div>
			</div>

            <div class="middle">
                <div class="wp">
                    <a href="{% url 'index' %}"><img class="fl" src="/static/images/logo.jpg"/></a>
                    <div class="searchbox fr">
                        <div class="selectContainer fl">
                            <span class="selectOption" id="jsSelectOption" {% ifequal '/' request.path  %}data-value="course">公开课{% endifequal %}
                            {% ifequal '/course/list' request.path|slice:'12' %}data-value="course">公开课{% endifequal %}
                            {% ifequal '/org/teacher/list' request.path|slice:'17'  %}data-value="teacher">授课老师{% endifequal %}
                            {% ifequal '/org/list' request.path|slice:'9'  %}data-value="org">课程机构{% endifequal %}
                            </span>
                            <ul class="selectMenu" id="jsSelectMenu">
                                <li data-value="course">公开课</li>
                                <li data-value="org">课程机构</li>
                                <li data-value="teacher">授课老师</li>
                            </ul>
                        </div>
                        <input id="search_keywords" class="fl" type="text" value="" placeholder="请输入搜索内容"/>
                        <img class="search_btn fr" id="jsSearchBtn" src="/static/images/search_btn.png"/>
                    </div>
                </div>
            </div>
            
            
			<nav>
				<div class="nav">
					<div class="wp">
						<ul>
							<li class="active" ><a href="{% url 'index' %}">首页</a></li>
							<li >
								<a href="{% url 'course:list' %}">
									公开课<img class="hot" src="/static/images/nav_hot.png">
								</a>
							</li>
							<li >
								<a href="{% url 'org:teacher_list' %}">授课教师</a>
							</li>
							<li ><a href="{% url 'org:org_list' %}">授课机构</a></li>
						</ul>
					</div>
				</div>
			</nav>
            
			</div>
    </header>
</section>
<!--crumbs start-->



    <div class="banner">
			<div class="wp">
				<div class="fl">
					<div class="imgslide">
						<ul class="imgs">
                                {% for banner in all_banner %}
                                <li>
                                    <a href="{{ banner.url }}" target="_blank">
                                        <img width="1200" height="478" src="{% static banner.image %}" />
                                    </a>
                                </li>
                                {% endfor %}
						</ul>
					</div>
					<div class="unslider-arrow prev"></div>
					<div class="unslider-arrow next"></div>
				</div>

				</div>


			</div>
<!--banner end-->
<!--feature start-->
	<section>
		<div class="wp">
			<ul class="feature">
				<li class="feature1">
					<img class="pic" src="/static/images/feature1.png"/>
					<p class="center">专业权威</p>
				</li>
				<li class="feature2">
					<img class="pic" src="/static/images/feature2.png"/>
					<p class="center">课程最新</p>
				</li>
				<li class="feature3">
					<img class="pic" src="/static/images/feature3.png"/>
					<p class="center">名师授课</p>
				</li>
				<li class="feature4">
					<img class="pic" src="/static/images/feature4.png"/>
					<p class="center">数据真实</p>
				</li>
			</ul>
		</div>
	</section>
<!--feature end-->
<!--module1 start-->
	<section>
		<div class="module">
			<div class="wp">
				<h1>公开课程</h1>
				<div class="module1 eachmod">
					<div class="module1_1 left">
						<img width="228" height="614" src="/static/images/module1_1.jpg"/>
						<p class="fisrt_word">名师授课<br/>专业权威</p>
						<a class="more" href="{% url 'course:list' %}">查看更多课程 ></a>
					</div>
					<div class="right group_list">
						<div class="module1_2 box">
							<div class="imgslide2">
								<ul class="imgs">
                                    {% for banner_course in banner_courses %}
                                    <li>
                                        <a href="{% url 'course:course_detail' banner_course.id %}">
                                            <img width="470" height="300" src="{% static banner_course.course_img %}" />
                                        </a>
                                    </li>
                                    {% endfor %}
								</ul>
							</div>
							<div class="unslider-arrow2 prev"></div>
							<div class="unslider-arrow2 next"></div>
						</div>
                        {% for course in courses %}
                        <div class="module1_3 box">
                                <a href="{% url 'course:course_detail' course.id %}">
                                    <img width="233" height="190" src="{% static course.course_img %}"/>
                                </a>
                                <div class="des">
                                    <a href="{% url 'course:course_detail' course.id %}">
                                        <h2 title="{{ course.name }}">{{ course.name }}</h2>
                                    </a>
                                    <span class="fl">难度：<i class="key">{{ course.get_degree_display }}</i></span>
                                    <span class="fr">学习人数：{{ course.students }}</span>
                                </div>
                                <div class="bottom">
                                    <span class="fl" title="{{ course.course_org }}">{{ course.course_org }}</span>
                                    <span class="star fr">{{ course.fav_nums }}</span>
                                </div>
                            </div>
                        {% endfor %}
					</div>
				</div>
			</div>
		</div>
	</section>
	<section>
		<div class="module greybg">
			<div class="wp">
				<h1>课程机构</h1>
				<div class="module3 eachmod">
					<div class="module3_1 left">
						<img width="228" height="463" src="/static/images/module3_1.jpg"/>
						<p class="fisrt_word">名校来袭<br/>权威认证</p>
						<a class="more" href="{% url 'org:org_list' %}">查看更多机构 ></a>
					</div>

                    <div class="right">
                    {% for course_org in course_orgs %}
						<ul>
                            <li class="{% if forloop.counter|divisibleby:'5' %}
                            five
                            {% endif %}">
                                <a href="org-detail-homepage.html">
                                    <div class="company">
                                        <img width="184" height="100" src="{% static course_org.image %}"/>
                                        <div class="score">
                                            <div class="circle">
                                                <h2>{{ course_org.tag }}</h2>
                                            </div>
                                        </div>
                                    </div>
                                    <p><span class="key" title="{{ course_org.name }}">{{ course_org.name }}</span></p>
                                </a>
                            </li>
						</ul>
                        {% endfor %}
					</div>

				</div>
			</div>
		</div>
	</section>

<footer>
		<div class="footer">
			<div class="wp">
				<ul class="cont">
					<li class="logo"><a href=""><img src="/static/images/footlogo.png"/></a></li>
					<li class="code"><img src="/static/images/code.jpg"/><p class="center">扫描关注微信</p></li>
					<li class="third"><img class="fl" src="/static/images/tell.png"/><p class="tell">33333333</p><p class="time">周一至周日 9:00-18:00</p></li>
				</ul>

			</div>
			<p class="line"></p>
			<div class="wp clear">
                <span class="fl">? 2016 www.projectsedu.com 慕学在线-在线学习交流平台 保留所有权利</span>
                <span class="fr">copyright ? 2016 ICP备案证书号：蜀ICP备xxxxx号-1</span>
			</div>
		</div>
	</footer>

<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>
<script src="/static/js/selectUi.js" type='text/javascript'></script>
<script src="/static/js/deco-common.js" type='text/javascript'></script>
<script type="text/javascript" src="/static/js/plugins/laydate/laydate.js"></script>
<script src="/static/js/plugins/layer/layer.js"></script>
<script src="/static/js/plugins/queryCity/js/public.js" type="text/javascript"></script>
<script src="/static/js/unslider.js" type="text/javascript"></script>
<script src="/static/js/plugins/jquery.scrollLoading.js"  type="text/javascript"></script>
<script src="/static/js/deco-common.js"  type="text/javascript"></script>

    <script type="text/javascript" src="/static/js/index.js"></script>

</body>
</html>

templates/usercenter-message.html
{% extends 'usercenter-info.html' %}
{% block title %}我的消息- 慕学在线网{% endblock %}
{% block custom_css %}{% endblock %}
{% block custom_three %}<li>我的消息</li>{% endblock %}
{% block right_content %}
<div class="right" >
		<div class="personal_des Releasecont">
			<div class="head">
				<h1>我的消息</h1>
			</div>

		</div>
		<div class="personal_des permessage">
			<div class="head">
				<ul class="tab_header messagehead">
					<li class="active"><a href="{% url 'users:my_message' %}">个人消息</a> </li>
				</ul>

			</div>
			<div class="messagelist">
                {% for message in all_message %}
                <div class="messages">
                        <div class="fr">
                            <div class="top"><span class="fl time">{{ message.add_time }}</span><span class="fr btn foldbtn"></span></div>
                            <p>
                                {{ message.message }}
                            </p>
                        </div>
                    </div>
                {% endfor %}

			</div>


			<div class="pageturn pagerright">
                <ul class="pagelist">
                    {% if all_message.has_previous %}
                        <li class="long"><a href="?page={{ all_message.previous_page_number }}">上一页</a></li>
                    {% endif %}
                    {% for nums in all_message.paginator.page_range %}
                        <li class="{% if all_message.number == nums %}active{% endif %}"><a href="?page={{ nums }}">{{ nums }}</a></li>
                    {% endfor %}
                    {% if all_message.has_next %}
                        <li class="long"><a href="?page={{ all_message.next_page_number }}">下一页</a></li>
                    {% endif %}


            </ul>
            </div>
		</div>

	</div>
{% endblock %}
{% block custom_js %}{% endblock %}